version: '3'

services:
  apache:
    build:
      ./httpd
    volumes:
      - ./src:/var/www/html
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php

  nginx:
    image: nginx:1.13
    ports:
      - 8081:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apache

  php:
    build:
          ./php
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
  db:
       image: mysql:5.7
       ports:
          - 8082:3306
       environment:
          - MYSQL_ROOT_PASSWORD=1111
          - MYSQL_DATABASE=iclub
          - MYSQL_USER=iclub
          - MYSQL_PASSWORD=1111
       volumes:
           - ./database:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=db
          - MYSQL_ROOT_PASSWORD=1111
      restart: always
      ports:
          - 8080:80
      volumes:
          - /sessions
      links:
           - db
